spring:
  application:
    name: auth-server
  config:
    import: "optional:configserver:http://localhost:8088"
jwt:
  secret-key: dbdbwdibwibdiubxiu3plwviduvi2oie3ghdgvsvdbibixbuieguibddblbibdvscvduibxiebubiixb
  expired: 36000000