server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    import: "optional:configserver:http://localhost:8088"
  application:
    name: agi-gateway-service
  cloud:
    gateway:
      routes:
        - id: employee-server
          uri: lb://employee-server
          predicates:
            - Path=/api/v1/employee/**
        - id: department-server
          uri: lb://department-server
          predicates:
            - Path=/api/v1/department/**
management:
  tracing:
    sampling:
      probability: 1.0
