version: "3.8"

services:
  employee-service:
    build: ../
    ports:
      - "8080:8080"
    container_name: employee-service
    environment:
      - EUREKA_URL=http://localhost:8761/eureka/
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_PASSWORD=elyor1202
      - DB_USERNAME=postgres
      - SERVER_PORT=8080
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=elyor1202
      - POSTGRES_USERNAME=postgres
    volumes:
      - test_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pg-admin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=elyor1202
volumes:
  test_volume: {}

